version: "3.9"

services:
  kai-backend:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [firebase]

  firebase:
    image: spine3/firebase-emulator:latest
    environment: [GCP_PROJECT=kai-local, ENABLE_UI=true]
    ports:
      - "8080:8080"   # Firestore
      - "9099:9099"   # Auth
      - "4000:4000"   # Emulator UI
    volumes: ["./firebase:/data"]

  # (Frontend to be added later)
